//Script GUID:59ede78d-cbec-4a6d-9335-89cb8acc1dc9
//Used for tracking history

colors1 = 
    VIEW @"/my/Demo/DynamicViews/ColorsUntyped.view" 
    PARAMS (
        Input = @"/my/Demo/DynamicViews/Colors.txt"
    );

colors2 = 
    VIEW @"/my/Demo/DynamicViews/ColorsTyped.view" 
    PARAMS 
    ( 
        Input = @"/my/Demo/DynamicViews/Colors.txt"
    );

OUTPUT colors1 
TO SSTREAM @"/my/Demo/DynamicViews/output-colors-untyped.ss";

OUTPUT colors2 
TO SSTREAM @"/my/Demo/DynamicViews/output-colors-typed.ss";
